project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: images/tall-logo.png
   
    left:
      - href: index.qmd
        text: TALL 
      - href: features.qmd
        text: Features
      - href: tall_ai.qmd
        text: TALL AI
      - href: documentation.qmd
        text: Documentation
      - href: download.qmd
        text: Download
      - href: usecases.qmd
        text: Use Cases       
      - href: about_us.qmd
        text: About Us

format:
  html:
    theme: mint
    css: styles.css
    include-after-body: _footer.html
    toc: true
